"""remove token

Revision ID: 027ab37d04da
Revises: 
Create Date: 2025-11-26 22:56:31.494775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027ab37d04da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('discord_token')
        batch_op.drop_column('google_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_token', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('discord_token', sa.VARCHAR(length=256), nullable=True))

    # ### end Alembic commands ###
